function [value,isterminal,direction] = Event_TD(t,in2)
%Event_TD
%    [VALUE,ISTERMINAL,DIRECTION] = Event_TD(T,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    05-Mar-2023 14:58:03

y1 = in2(1,:);
value = y1;
if nargout > 1
    isterminal = 1.0;
end
if nargout > 2
    direction = -1.0;
end
