function out1 = FFB_function(t,in2)
%FFB_function
%    OUT1 = FFB_function(T,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    05-Mar-2023 14:58:03

y2 = in2(2,:);
out1 = [y2;-9.81e+2./1.0e+2];
